import type { Metadata } from "next";
import ScrollProvider from "@/components/providers/ScrollProvider";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "home",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <ScrollProvider>
        <main>{children}</main>
      </ScrollProvider>
      <Footer />
    </div>
  );
}